In [1]:
import numpy as np

#### Arrays X Listas

In [10]:
a = [1, 2, 3, 4]
b = [4, 8, 3, 1]

In [9]:
# Qual o resultado de a + b ?
# Qual o resultado de a - b ?
# Qual o resultado de a*3 ?
print(a+b)
print(a*3)

[1, 2, 3, 4, 4, 8, 3, 1]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [11]:
a_np = np.array([1, 2, 3, 4])
b_np = np.array([4, 8, 3, 1])

In [13]:
# Qual o resultado de a_np + b_np ?
# Qual o resultado de a_np - b_np ?
# Qual o resultado de a_np*3 ?
print(a_np + b_np)
print(a_np - b_np)
print(a_np*3)

[ 5 10  6  5]
[-3 -6  0  3]
[ 3  6  9 12]


#### Matrizes (arrays n-dimensional)

In [15]:
M = np.array([[1,2], [0,2], [2,1]])
print(M)

[[1 2]
 [0 2]
 [2 1]]


In [16]:
M.shape

(3, 2)

In [23]:
# Primeira Linha
print(M[0])
# Primeira coluna
print(M[:,0])
# Subset da matriz
print(M[:2, :2])

[1 2]
[1 0 2]
[[1 2]
 [0 2]]


In [24]:
# Atribui valor a um elemento específico
M[0,0] = 10
print(M)

[[10  2]
 [ 0  2]
 [ 2  1]]


#### Operações com Numpy

1. Operações Matemáticas

In [25]:
print(np.array([0, np.pi/2, np.pi]))

[0.         1.57079633 3.14159265]


In [26]:
print(np.cos(0),  np.sin(0))

1.0 0.0


2. Operações de Redimensionamento e Transposição

In [27]:
M = np.array([[1,2], [0,2], [2,1]])
print(M)

[[1 2]
 [0 2]
 [2 1]]


In [29]:
# Transposição
M.T

array([[1, 0, 2],
       [2, 2, 1]])

In [31]:
M.transpose()

array([[1, 0, 2],
       [2, 2, 1]])

In [32]:
# Redimensionamento
M.reshape((2,3))

array([[1, 2, 0],
       [2, 2, 1]])

In [34]:
M.reshape((2,2))

ValueError: cannot reshape array of size 6 into shape (2,2)

3. Operações de Algebra Linear

In [35]:
x = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])

Combinação linear: $\ x_1*w_1 + x_2*w_2 + x_3*w_3+ . . . + x_m*w_m$

In [38]:
sum(x*w)

np.int64(70)

In [43]:
np.dot(x,w)

np.int64(70)

Multiplicação de Matrizes

In [44]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [49]:
a@b

array([[19, 22],
       [43, 50]])

Matriz Inversa: $\ A^{-1} . A = I$

In [50]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])